
MPFR_HOST_VERSION := $(subst ",,$(strip $(CONFIG_EMBTK_MPFR_HOST_VERSION_STRING)))
MPFR_HOST_SITE := http://www.mpfr.org/mpfr-$(MPFR_HOST_VERSION)
MPFR_HOST_COMPRESSOR := tar.bz2
MPFR_HOST_COMPRESSOR_FLAGS := -xjf
MPFR_HOST_DECOMPRESSOR := tar
MPFR_HOST_PACKAGE := mpfr-$(MPFR_HOST_VERSION).$(MPFR_HOST_COMPRESSOR)
MPFR_HOST_BUILD_DIR := $(TOOLS_BUILD)/$(MPFR_HOST_PACKAGE)

DOWNLOAD_MPFR_HOST:
	@test -e $(DOWNLOAD_DIR)/$(MPFR_HOST_PACKAGE) || \
	wget -P $(DOWNLOAD_DIR) $(MPFR_HOST_SITE)/$(MPFR_HOST_PACKAGE)

BUILD_MPFR_HOST: $(DECROMPRESS_MPFR_HOST) $()
